version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-rootpassword}
      MONGO_INITDB_DATABASE: downloads
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  
  app:
    image: 0xd0a/burn-after-read
    restart: always
    ports:
      - 3001:3001
    environment:
      ADMIN_PASSWORD: ""
      PORT: 3001